### ISSUE TITLE
Activity not working 

### ISSUE THREAD

**Issue by ayushnawal** [sugarlabs/tuxpaint-wrapper-activity#2]
On running the activity using `sugar-activity .` displays this in logs;

> Traceback (most recent call last):
  File "/usr/local/bin/sugar-activity", line 5, in <module>
    activityinstance.main()
  File "/usr/local/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 230, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/local/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 59, in create_activity_instance
    activity = constructor(handle)
  File "/home/ayush/activities/tuxpaint-wrapper-activity/activity.py", line 47, in __init__
    proc = subprocess.Popen(options)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by quozl** [comment]
Install tuxpaint.  See https://github.com/sugarlabs/tuxpaint-wrapper-activity#how-to-upgrade
